[build]
target-dir = "target"

[target.'cfg(all(target_arch = "x86_64"))']
rustflags = ["-C", "target-cpu=native"]

[profile.secure]
inherits = "release"
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"
overflow-checks = true