[package]
name = "kindly-guard-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.kindlyguard.dev/cli"
readme = "README.md"
keywords = ["security", "cli", "scanner", "unicode", "threat-detection"]
categories = ["command-line-utilities", "security"]
description = "Command-line security scanner and monitoring tool for threat detection"

[[bin]]
name = "kindly-guard-cli"
path = "src/main.rs"

[dependencies]
# Workspace dependencies
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

# CLI
clap = { version = "4.5", features = ["derive"] }

# File operations
walkdir = "2.5"
ignore = "0.4"

# Progress bars
indicatif = "0.17"

# Time handling
chrono = "0.4"

# Output formatting
colored = "2.1"
comfy-table = "7.1"

# HTTP client (for remote scanning)
reqwest = { version = "0.12", features = ["json"] }

# Scanner integration
kindly-guard-server = { path = "../kindly-guard-server" }

[dev-dependencies]
tempfile = "3.14"
assert_cmd = "2.0"
predicates = "3.1"
nix = { version = "0.29", features = ["signal"] }