codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 1%
        base: auto
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "**/*.rs.bk"
  - "**/tests/**"
  - "**/benches/**"
  - "**/examples/**"
  - "kindly-guard-core/**"  # Private dependency