#\!/bin/bash
echo "Checking latest versions of critical dependencies:"
echo "================================================"
cargo search tokio --limit 1  < /dev/null |  grep "^tokio ="
cargo search serde --limit 1 | grep "^serde ="
cargo search serde_json --limit 1 | grep "^serde_json ="
cargo search regex --limit 1 | grep "^regex ="
cargo search sha2 --limit 1 | grep "^sha2 ="
cargo search base64 --limit 1 | grep "^base64 ="
cargo search anyhow --limit 1 | grep "^anyhow ="
cargo search thiserror --limit 1 | grep "^thiserror ="
cargo search clap --limit 1 | grep "^clap ="
cargo search uuid --limit 1 | grep "^uuid ="
cargo search chrono --limit 1 | grep "^chrono ="
cargo search notify --limit 1 | grep "^notify ="
cargo search axum --limit 1 | grep "^axum ="
cargo search flate2 --limit 1 | grep "^flate2 ="
cargo search toml --limit 1 | grep "^toml ="
