# Clippy configuration for KindlyGuard

# Maximum allowed cognitive complexity
cognitive-complexity-threshold = 30

# Maximum number of lines in a function
too-many-lines-threshold = 100

# Maximum number of arguments to a function
too-many-arguments-threshold = 7

# Maximum size of an enum variant
enum-variant-size-threshold = 200

# Disallowed names
disallowed-names = ["foo", "bar", "baz", "test"]