# cargo-deny configuration for KindlyGuard

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# List of explicitly disallowed crates
deny = [
    # Heavy dependencies explicitly forbidden in project configuration
    { name = "reqwest", reason = "Too heavy - use hyper/axum instead" },
    { name = "diesel", reason = "Too heavy - use lighter alternatives" },
    { name = "actix-web", reason = "Too heavy - use axum instead" },
]

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "Zlib",
    "0BSD",
    "BSL-1.0",
    "MPL-2.0",
    "Unlicense",
]
# Confidence threshold for license detection
confidence-threshold = 0.9

[sources]
# Lint level for what to happen when a crate from a git repository is detected
unknown-git = "warn"
# Lint level for what to happen when a crate from a registry that is not crates.io is detected
unknown-registry = "warn"
# List of allowed registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# A list of advisory IDs to ignore
ignore = [
    # paste is unmaintained but used by ratatui - acceptable for now
    "RUSTSEC-2024-0436",
]