# Minimal KindlyGuard Configuration for Testing

# Server configuration
[server]
stdio = true

# Scanner configuration
[scanner]
unicode_detection = true
injection_detection = true
path_traversal_detection = true

# Shield display configuration
[shield]
enabled = true

# Authentication configuration
[auth]
enabled = false

# Signing configuration
[signing]
enabled = false

# Rate limiting configuration
[rate_limit]
enabled = true
requests_per_minute = 60
burst_size = 10

# Event processor configuration
[event_processor]
enabled = false

# Telemetry configuration
[telemetry]
enabled = false

# Storage configuration
[storage]
provider = "memory"

# Plugin configuration
[plugins]
enabled = false

# Audit configuration
[audit]
enabled = false

# Transport configuration
[transport]
stdio = true

# Resilience configuration
[resilience]
enhanced_mode = false

[resilience.circuit_breaker]
failure_threshold = 5
recovery_timeout = "30s"
half_open_max_requests = 3

[resilience.retry]
max_attempts = 3
initial_delay = "100ms"
max_delay = "10s"
jitter_factor = 0.1
timeout = "30s"