[server]
port = 8080
stdio = true

[scanner]
unicode_detection = true
injection_detection = true
enable_event_buffer = true  # Enables patented atomic event buffer in scanner

[shield]
enabled = true  # Must use --shield flag to see display
update_interval_ms = 500
detailed_stats = true
color = true

[auth]
enabled = true

[signing]
enabled = true
algorithm = "hmac_sha256"
hmac_secret = "ZGVtby1zZWNyZXQta2V5LWZvci1wdXJwbGUtc2hpZWxkLWRlbW8="

[rate_limit]
enabled = true
default_rpm = 60
burst_capacity = 10

[event_processor]
# ENABLE THIS FOR PURPLE SHIELD MODE
enabled = true  # <-- When true, shield turns purple!
buffer_size_mb = 20
max_endpoints = 1000
rate_limit = 10000.0
pattern_detection = true
correlation_enabled = true
