#!/bin/bash
# Release commands for KindlyGuard v0.9.4

echo "KindlyGuard v0.9.4 Release Commands"
echo "==================================="
echo ""
echo "1. First, ensure all changes are committed:"
echo ""
echo "git add -A"
echo "git commit -m \"chore: bump version to v0.9.4"
echo ""
echo "Updates:"
echo "- Updated all Cargo.toml files to version 0.9.4"
echo "- Updated npm package.json to version 0.9.4"
echo "- Added cross-platform build support"
echo "- Fixed missing platform binaries for macOS and Windows\""
echo ""
echo "2. Create and push the release tag:"
echo ""
echo "git tag -a v0.9.4 -m \"Release v0.9.4 - Cross-platform support and NPM fixes"
echo ""
echo "Key improvements:"
echo "- Fixed missing platform binaries in NPM package"
echo "- Added proper cross-platform build support"
echo "- Enhanced build scripts for all platforms"
echo "- NPM package now correctly supports Linux, macOS, and Windows\""
echo ""
echo "3. Push the changes and tag:"
echo ""
echo "git push origin master"
echo "git push origin v0.9.4"
echo ""
echo "4. Create GitHub release:"
echo ""
echo "After pushing, create a GitHub release at:"
echo "https://github.com/samduchaine/kindly-guard/releases/new"
echo ""
echo "- Tag: v0.9.4"
echo "- Title: KindlyGuard v0.9.4 - Cross-platform NPM Support"
echo "- Attach release notes from RELEASE_NOTES_v0.9.4.md"
echo "- Upload binaries from dist/ directory"
echo "- Include SHA256SUMS.txt"
echo ""
echo "5. Publish to NPM (if not using CI):"
echo ""
echo "cd npm-package"
echo "npm publish"
echo ""
echo "6. Publish to crates.io:"
echo ""
echo "cd kindly-guard-server && cargo publish"
echo "cd ../kindly-guard-cli && cargo publish"
echo "cd ../crates-io-package/kindlyguard && cargo publish"