# Rust toolchain configuration for KindlyGuard
# This file ensures consistent Rust versions across all contributors
# and CI environments.

[toolchain]
# Use the MSRV (Minimum Supported Rust Version) for development
# This ensures we don't accidentally use features from newer versions
channel = "1.80.0"
components = [
    "rustfmt",
    "clippy",
    "rust-src",
    "rust-docs",
    "rustc-dev",
    "llvm-tools",
]
profile = "default"

# Override targets for cross-compilation support
# These are commonly needed for security testing and deployment
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "wasm32-unknown-unknown",
]