# KindlyGuard Test Configuration

[server]
port = 8080
stdio = true
max_connections = 100
request_timeout_secs = 30

[scanner]
unicode_detection = true
injection_detection = true
path_traversal_detection = true
max_scan_depth = 10
enable_event_buffer = false

[shield]
enabled = false
update_interval_ms = 1000
detailed_stats = true
color = true

[auth]
enabled = false
trusted_issuers = []
cache_ttl_seconds = 300
validate_resource_indicators = true
jwt_secret = ""
require_signature_verification = false

[auth.required_scopes]
default = []

[auth.required_scopes.tools]

[auth.required_scopes.resources]

[signing]
enabled = false
algorithm = "hmac_sha256"
hmac_secret = ""
ed25519_private_key = ""
require_signatures = false
grace_period_seconds = 60
include_timestamp = true
max_clock_skew_seconds = 300

[rate_limit]
enabled = true
default_rpm = 60
burst_capacity = 10
cleanup_interval_secs = 300
adaptive = false
threat_penalty_multiplier = 0.5

[rate_limit.method_limits]

[rate_limit.client_limits]

[event_processor]
enabled = false

[telemetry]
enabled = false
service_name = "kindly-guard"
service_version = "0.1.0"
export_endpoint = ""
export_interval_seconds = 60
tracing_enabled = true
metrics_enabled = true
sampling_rate = 0.1

[storage]
enabled = true
storage_type = "memory"
data_dir = ""
connection_string = ""
retention_days = 7
archive_after_days = 30
max_storage_mb = 100
compression = false
encryption_at_rest = false
max_events = 10000

[plugins]
enabled = false
plugin_dirs = []
auto_load = false
allowlist = []
denylist = []
max_execution_time_ms = 5000
isolation_level = "standard"

[audit]
enabled = true
backend = "memory"
retention_days = 7
max_events = 1000
buffer_size = 100
file_path = ""
compress = false
encrypt = false
custom_config = {}

[transport]
multiplexing = false

[transport.timeouts]
connect_ms = 5000
read_ms = 30000
write_ms = 30000
idle_ms = 300000

[transport.security]
require_tls = false
min_tls_version = "1.2"
cipher_suites = []
encryption = false

[transport.security.client_auth]
required = false
ca_certs = []
verify_depth = 3

[transport.buffers]
recv_buffer_size = 65536
send_buffer_size = 65536
message_queue_size = 1000

[[transport.transports]]
transport_type = "stdio"
enabled = true
config = {}