[build]
# Always use release profile for security
# Even debug builds should have some optimizations
rustflags = ["-C", "opt-level=1", "-C", "overflow-checks=on"]

[profile.secure]
# Custom secure build profile
inherits = "release"
lto = true
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = true

[target.'cfg(all())']
# Security-focused lints
rustflags = [
    "-W", "unsafe_code",
    "-W", "missing_docs",
    "-W", "rust_2018_idioms",
    "-W", "clippy::all",
    "-W", "clippy::pedantic",
    "-W", "clippy::nursery",
    "-W", "clippy::cargo",
    # Allow some common patterns
    "-A", "clippy::module_name_repetitions",
    "-A", "clippy::must_use_candidate",
    "-A", "clippy::missing_errors_doc",
    # Deny security-critical lints
    "-D", "clippy::unwrap_used",
    "-D", "clippy::expect_used",
    "-D", "clippy::panic",
    "-D", "clippy::unimplemented",
    "-D", "clippy::todo",
]

[alias]
# Useful cargo aliases
audit = "audit --deny warnings"
secure-build = "build --profile=secure"
secure-test = "test --profile=secure"
lint = "clippy --all-features -- -D warnings"