[alias]
# Convenience alias for running xtask
xtask = "run --package xtask --"

# Other useful aliases
br = "build --release"
ba = "build --all-features"
ta = "test --all-features"
sec = "xtask security --all"