[workspace]
members = ["src-tauri"]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"

[profile.secure]
inherits = "release"
overflow-checks = true